name: Tests
on: [push, pull_request]
concurrency:
  group: tests-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Get dependencies
      run: |
        # Needed for github.com/google/go-tspi/tspi
        # in opensuse this is trousers-devel
        sudo add-apt-repository ppa:smoser/swtpm
        sudo apt-get update
        sudo apt-get install libtspi-dev swtpm
        swtpm socket --server type=unixio,path=/tmp/tpm-server --ctrl type=unixio,path=/tmp/tpm-ctrl --tpm2 -d
        go get github.com/onsi/ginkgo/v2/ginkgo
        go get github.com/onsi/gomega/...
    - name: Run tests
      run: |
        # Disable tests with swtpm, as not currently working
        ginkgo -r ./...